id: opecha:P001685
initial_creation_type: ocr
source_metadata:
  id: bdr:W23780
  title: ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པའི་མན་ངག་གི་བསྟན་བཅོས་མངོན་པར་རྟོགས་པའི་རྒྱན་གྱི་འགྲེལ་པ་བློ་གསལ་ཐོག་མའི་འཇུག་ངོགས་རིན་པོ་ཆེ་ཐེམ་སྐས
  volume: ''
  author: ''
