id: P001685
initial_creation_type: ocr
source_metadata:
  id: bdr:W23780
  title: ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པའི་མན་ངག་གི་བསྟན་བཅོས་མངོན་པར་རྟོགས་པའི་རྒྱན་གྱི་འགྲེལ་པ་བློ་གསལ་ཐོག་མའི་འཇུག་ངོགས་རིན་པོ་ཆེ་ཐེམ་སྐས
  author: ''
  volumes:
    fc70dedbfa624167bce0716e74442c3c:
      image_group_id: I2759
      title: ''
      volume_number: 1
      total_pages: 502
      base_file: v001.txt
